Refactor: Add remove/add nodes api
datafuselabs/openraft pull request #250
Opened 2022-03-15 08:35 UTC by lichuang

Add remove/add nodes api

related issue:https://github.com/datafuselabs/openraft/issues/246

2022-03-15 09:22 UTC, schreter reviewed
Some more or less technical comments, I defer the semantic changes review to the others :-).

Otherwise, thanks for the implementation, it will help to make some use cases simpler.

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/250#-:-MyBsXli1jUgpiAZAQzv:blo1svr)* status: all files reviewed, 16 unresolved discussions (waiting on @ariesdevil, @drmingdrmer, and @lichuang)

___
*[openraft/src/raft.rs, line 409 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBrGxT2mt262A52XiC:-MyBrGxT2mt262A52XiD:bqiponw) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/raft.rs#L409)):*
> ```XML
>         turn_to_learner: bool,
>     ) -> Result<ClientWriteResponse<C>, ClientWriteError<C>> {
>         tracing::info!("remove_nodes: start to commit joint config");
> ```

You definitely don't want this as info. Probably level `trace` or `debug` is the right one here.
___
*[openraft/src/raft.rs, line 426 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBrHVRA1NwOa1pjuHy:-MyBrHVRA1NwOa1pjuHz:b-2guby3) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/raft.rs#L426)):*
> ```XML
>             .await?;
> 
>         tracing::info!("res of first remove_nodes: {:?}", res.summary());
> ```

same here
___
*[openraft/src/raft.rs, line 435 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBr5dT13SuWiPopZAS:-MyBr5dT13SuWiPopZAT:b-qu24m0) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/raft.rs#L435)):*
> ```XML
>         }
> 
>         tracing::debug!("committed a joint config: {} {:?}", log_id, joint);
> ```

Also these traces seem like not quite finished during development. Maybe join into one trace statement and probably lower the trace level to `trace`.



_Code quote:_
```XML
        tracing::debug!("committed a joint config: {} {:?}", log_id, joint);
        tracing::debug!(
            "the second step is to remove_nodes to uniform config: {:?}",
            remove_members
        );
```
___
*[openraft/src/raft.rs, line 454 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBr4L23VO4zsEte8_1:-MyBr4L23VO4zsEte8_2:b-2guby3) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/raft.rs#L454)):*
> ```XML
>             .await?;
> 
>         tracing::info!("res of second remove_nodes: {}", res.summary());
> ```

same here
___
*[openraft/src/raft.rs, line 465 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBrImX8clKt7JTdKVb:-MyBrImX8clKt7JTdKVc:b-2guby3) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/raft.rs#L465)):*
> ```XML
>         blocking: bool,
>     ) -> Result<ClientWriteResponse<C>, ClientWriteError<C>> {
>         tracing::info!("add_nodes: start to commit joint config");
> ```

same here
___
*[openraft/src/raft.rs, line 481 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBrJbz83y6o2WBsXpy:-MyBrJc-7hyT50JdjbWc:b-2guby3) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/raft.rs#L481)):*
> ```XML
>             .await?;
> 
>         tracing::info!("res of first add_nodes: {:?}", res.summary());
> ```

same here
___
*[openraft/src/raft.rs, line 490 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBrL0Q9alSkiY4UCIg:-MyBrL0Q9alSkiY4UCIh:b-2guby3) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/raft.rs#L490)):*
> ```XML
>         }
> 
>         tracing::debug!("committed a joint config: {} {:?}", log_id, joint);
> ```

same here



_Code quote:_
```XML
        tracing::debug!("committed a joint config: {} {:?}", log_id, joint);
        tracing::debug!("the second step is to add_nodes to uniform config: {:?}", add_members);
```
___
*[openraft/src/raft.rs, line 505 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBrLnU9rBMavo3zxpk:-MyBrLnU9rBMavo3zxpl:b-2guby3) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/raft.rs#L505)):*
> ```XML
>             .await?;
> 
>         tracing::info!("res of second add_nodes: {}", res.summary());
> ```

same here
___
*[openraft/src/raft.rs, line 695 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBrWLt2zReCbj4ie-j:-MyBrWLt2zReCbj4ie-k:b-uuws8u) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/raft.rs#L695)):*
> ```XML
>         ///
>         /// Otherwise, wait for commit of the member change log.
>         blocking: bool,
> ```

grammar



_Suggestion:_
```XML
        /// If `blocking` is `false`, respond to the client with a `ChangeMembershipError::LearnerIsLagging` error at once if a
        /// non-member is lagging.
        ///
        /// Otherwise, wait for the commit of the member change log.
```
___
*[openraft/src/raft.rs, line 697 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBrl-C1qnrWrV4J-lc:-MyBrl-C1qnrWrV4J-ld:b-uuws8u) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/raft.rs#L697)):*
> ```XML
>         blocking: bool,
> 
>         /// If turn_to_learner is true, then all the members which not exists in the new membership,
> ```

grammar



_Suggestion:_
```XML
        /// If `turn_to_learner` is `true`, then all the members which do not exist in the new membership
        /// will be turned into learners, otherwise they will be removed.
```
___
*[openraft/src/raft.rs, line 710 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBs6naDnN0Gs4oHFi5:-MyBs6naDnN0Gs4oHFi6:b-uuws8u) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/raft.rs#L710)):*
> ```XML
>         ///
>         /// Otherwise, wait for commit of the member change log.
>         blocking: bool,
> ```

grammar



_Suggestion:_
```XML
        /// If `blocking` is `false`, respond to the client with a `ChangeMembershipError::LearnerIsLagging` error at once if a
        /// non-member is lagging.
        ///
        /// Otherwise, wait for the commit of the member change log.
```
___
*[openraft/src/core/admin.rs, line 162 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBmlBq2ocEtsW6TYdZ:-MyBmlBq2ocEtsW6TYd_:b-fi0imf) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/core/admin.rs#L162)):*
> ```XML
>     }
> 
>     fn has_pending_config(&self) -> bool {
> ```

Maybe add the method documentation?
___
*[openraft/src/core/admin.rs, line 232 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBn4Uu2QV_kNY3B5i7:-MyBn4Uu2QV_kNY3B5i8:b-nq5sb2) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/core/admin.rs#L232)):*
> ```XML
>     ) -> Result<(), StorageError<C>> {
>         // Ensure cluster will have at least one node.
>         if remove_members.is_empty() {
> ```

You could check this already on the API level. But, it's also OK here.
___
*[openraft/src/core/admin.rs, line 308 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBnsZ67fdQqMOejsDj:-MyBnsZ67fdQqMOejsDk:bhh6q7a) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/core/admin.rs#L308)):*
> ```XML
>         tracing::debug!(?new_config, "new_config");
> 
>         match self.is_all_new_members_line_rate(add_members, blocking) {
> ```

You can write it more concise like this:



_Suggestion:_
```XML
        if let Err(e) = self.is_all_new_members_li [...]

2022-03-15 09:45 UTC, drmingdrmer requested changes
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/250)* status: all files reviewed, 17 unresolved discussions (waiting on @ariesdevil and @lichuang)

___
*[openraft/src/raft.rs, line 420 at r2](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBwVJj3IkVv6-gXrtq:-MyBwVJj3IkVv6-gXrtr:b-5cdgea) ([raw file](https://github.com/datafuselabs/openraft/blob/08f468a6246b7e761e995c0698e4bb7a9d3cf725/openraft/src/raft.rs#L420)):*
> ```XML
>                     blocking,
>                     turn_to_learner,
>                     tx,
> ```

Instead of introducing another two variants to `RaftMsg`, it might make things simpler by making `RaftMsg::ChangeMembership::members` an enum: 
```rust
enum ChangeMembers {
    Add(BTreeSet<C::NodeId>,
    Remove(BTreeSet<C::NodeId>,
    Replace(BTreeSet<C::NodeId>,
}
enum RaftMsg {
    ChangeMembership {
        members: ChangeMembers,
    },
}
```



_Code quote:_
```XML
                RaftMsg::RemoveNodes {
                    members: remove_members.clone(),
                    blocking,
                    turn_to_learner,
                    tx,
```


<!-- Sent from Reviewable.io -->

2022-03-16 03:42 UTC, lichuang reviewed
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/250)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ariesdevil, @drmingdrmer, and @schreter)

___
*[openraft/src/raft.rs, line 420 at r2](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBwVJj3IkVv6-gXrtq:-MyFnoZiEp9kTuPuZ8qG:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/08f468a6246b7e761e995c0698e4bb7a9d3cf725/openraft/src/raft.rs#L420)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Instead of introducing another two variants to `RaftMsg`, it might make things simpler by making `RaftMsg::ChangeMembership::members` an enum: 
```rust
enum ChangeMembers {
    Add(BTreeSet<C::NodeId>,
    Remove(BTreeSet<C::NodeId>,
    Replace(BTreeSet<C::NodeId>,
}
enum RaftMsg {
    ChangeMembership {
        members: ChangeMembers,
    },
}
```
</blockquote></details>

Done.
___
*[openraft/src/membership/membership.rs, line 365 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBqCpKBa4rgjQ8swrw:-MyFoDcJ0EBshGHO4OwL:b8sh7ij) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/membership/membership.rs#L365)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Wouldn't this suffice?
</blockquote></details>

Thank your advice, in your way will be more elegant.


<!-- Sent from Reviewable.io -->

2022-03-16 06:50 UTC, drmingdrmer commented on openraft/src/core/admin.rs
> +        self.change_membership(new_members, blocking, false, tx).await?;
You do not need to call `curr.remote_members`. Just removing node ids from the last config is enough:
```rust
let new_members = self.core.effective_membership.membership.get_configs().last().cloned().difference(remove_members).collect()
```

2022-03-16 06:55 UTC, drmingdrmer commented on openraft/src/raft.rs
> +        }
There is already empty membership check in the `LeaderState::change_membership()`.
This may not be necessary.

2022-03-16 06:58 UTC, drmingdrmer commented on openraft/src/raft.rs
> +    pub async fn remove_members(
The body of `change_membership()`, `remove_members()` and `add_members()` are almost the same.
The common part can be extracted into another method to reduce duplicated codes.

2022-03-16 07:34 UTC, drmingdrmer commented on openraft/src/core/mod.rs
> +            },
It looks like by moving this `match` into `self.change_membership()` it will get rid of about 50 lines of code.

2022-03-16 07:35 UTC, drmingdrmer commented on openraft/src/membership/membership.rs
> +
These two methods can be removed now. Otherwise, the method names should be updated to reflect their actual behavior.

2022-03-16 07:54 UTC, schreter reviewed
> Reviewed 2 of 6 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/250)* status: all files reviewed, 8 unresolved discussions (waiting on @ariesdevil, @drmingdrmer, and @lichuang)

___
*[.github/workflows/ci.yaml, line 31 at r5](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyGhVCpEIdeKDFe1JNV:-MyGhVCqEbPrkJCsesol:b-gbq5fh) ([raw file](https://github.com/datafuselabs/openraft/blob/dfabd41d91e99b5c58c029f09f5ad40ab1fd5e1a/.github/workflows/ci.yaml#L31)):*
> ```YAML
>         env:
>           # Parallel tests block each other and result in timeout.
>           RUST_TEST_THREADS: 1
> ```

What is the background of these changes?

These changes don't seem related to the PR, though they will help with making tests more deterministic. Still, specialized time-simulating test runtime is the only solution to make them fully-deterministic and to test all corner cases.
___
*[openraft/src/raft.rs, line 697 at r1](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBrl-C1qnrWrV4J-lc:-MyGf-SN8Q-OPraDPhQW:bdqmc9b) ([raw file](https://github.com/datafuselabs/openraft/blob/04ac7a707cc4d1fc371ea56f58c5d7067a6f90e1/openraft/src/raft.rs#L697)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

grammar
</blockquote></details>

The grammar is still wrong (also above for `blocking`).
___
*[openraft/src/raft.rs, line 329 at r5](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyGfQsA2hTNfkgdUDfT:-MyGfQsB0hsUPCxRYIjN:b4oukc4) ([raw file](https://github.com/datafuselabs/openraft/blob/dfabd41d91e99b5c58c029f09f5ad40ab1fd5e1a/openraft/src/raft.rs#L329)):*
> ```XML
>         turn_to_learner: bool,
>     ) -> Result<ClientWriteResponse<C>, ClientWriteError<C>> {
>         tracing::info!("do_change_membership: start to commit joint config");
> ```

I see that here it's also tracing with `info` level. Maybe that's why you closed the comments on tracing w/o answering? OK, for lifecycle events, like membership change, that would be appropriate, but in a larger system (like we want to use - with 1000 of consensus domains), this will likely just unnecessarily pollute the trace.

Anyway, the trace level discussion is out-of-scope of this change.


<!-- Sent from Reviewable.io -->

2022-03-16 08:25 UTC, lichuang reviewed
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/250)* status: 3 of 7 files reviewed, 7 unresolved discussions (waiting on @ariesdevil, @drmingdrmer, and @schreter)

___
*[.github/workflows/ci.yaml, line 31 at r5](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyGhVCpEIdeKDFe1JNV:-MyGoF0LAxWHs-0UlE-C:b8zaw1k) ([raw file](https://github.com/datafuselabs/openraft/blob/dfabd41d91e99b5c58c029f09f5ad40ab1fd5e1a/.github/workflows/ci.yaml#L31)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

What is the background of these changes?

These changes don't seem related to the PR, though they will help with making tests more deterministic. Still, specialized time-simulating test runtime is the only solution to make them fully-deterministic and to test all corner cases.
</blockquote></details>

emm,  some time this cases run out of time:

test t16_change_membership_cases::add_remove_nodes_cases has been running for over 60 seconds
test t16_change_membership_cases::change_membership_cases has been running for over 60 seconds

i guess the reason is that when there is more unit tests run parallel.
___
*[openraft/src/raft.rs, line 362 at r4](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBhucspaHS8zQrMZeV-r4-362:-MyGodca72R5GUEn_QkQ:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/8e4f8da3840ac49d5e4f5401edbf0fa2bf8c67e4/openraft/src/raft.rs#L362)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

There is already empty membership check in the `LeaderState::change_membership()`.
This may not be necessary.
</blockquote></details>

Done.
___
*[openraft/src/raft.rs, line 411 at r4](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBhucspaHS8zQrMZeV-r4-411:-MyGog8_3ARZ9CAR37qF:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/8e4f8da3840ac49d5e4f5401edbf0fa2bf8c67e4/openraft/src/raft.rs#L411)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

The body of `change_membership()`, `remove_members()` and `add_members()` are almost the same.
The common part can be extracted into another method to reduce duplicated codes.

</blockquote></details>

Done.
___
*[openraft/src/core/admin.rs, line 243 at r4](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBhucspaHS8zQrMZeR-r4-243:-MyGp9Um8xiHQ9DiPDdO:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/8e4f8da3840ac49d5e4f5401edbf0fa2bf8c67e4/openraft/src/core/admin.rs#L243)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

You do not need to call `curr.remote_members`. Just removing node ids from the last config is enough:
```rust
let new_members = self.core.effective_membership.membership.get_configs().last().cloned().difference(remove_members).collect()
```
</blockquote></details>

Done.
___
*[openraft/src/core/mod.rs, line 953 at r5](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBhucspaHS8zQrMZeS-r5-953:-MyGpBSE6APY0xP-JKgY:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/dfabd41d91e99b5c58c029f09f5ad40ab1fd5e1a/openraft/src/core/mod.rs#L953)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

It looks like by moving this `match` into `self.change_membership()` it will get rid of about 50 lines of code.
</blockquote></details>

Done.
___
*[openraft/src/membership/membership.rs, line 367 at r5](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyBhucspaHS8zQrMZeT-r5-367:-MyGpCNzB6LwnL5st_dh:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/dfabd41d91e99b5c58c029f09f5ad40ab1fd5e1a/openraft/src/membership/membership.rs#L367)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

These two methods can be removed now. Otherwise, the method names should be updated to reflect their actual behavior.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-16 10:22 UTC, drmingdrmer requested changes
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/250)* status: 2 of 7 files reviewed, 11 unresolved discussions (waiting on @ariesdevil, @drmingdrmer, @lichuang, and @schreter)

___
*[openraft/tests/membership/t16_change_membership_cases.rs, line 72 at r8](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyHBpwy13v9DyCFI9NW:-MyHBpwy13v9DyCFI9NX:bdh57qe) ([raw file](https://github.com/datafuselabs/openraft/blob/f666fc923034b95b6234acd1f594e245fcdcc0ee/openraft/tests/membership/t16_change_membership_cases.rs#L72)):*
> ```XML
>         old.clone(),
>         only_in_new.cloned().collect::<BTreeSet<_>>(),
>         only_in_old.cloned().collect::<BTreeSet<_>>(),
> ```

These cases are not meant for add/remove member tests.
It's a bit redundant and not very clear about what it tries to prove.



_Code quote:_
```XML
async fn add_remove_nodes_cases() -> anyhow::Result<()> {
    let (_log_guard, ut_span) = init_ut!();

    async {
        change_from_to_with_add_remove_nodes(btreeset! {0}, btreeset! {1}).await?;
        change_from_to_with_add_remove_nodes(btreeset! {0}, btreeset! {1,2}).await?;
        change_from_to_with_add_remove_nodes(btreeset! {0}, btreeset! {1,2, 3}).await?;
        change_from_to_with_add_remove_nodes(btreeset! {0, 1}, btreeset! {1, 2}).await?;
        change_from_to_with_add_remove_nodes(btreeset! {0, 1}, btreeset! {1}).await?;
        change_from_to_with_add_remove_nodes(btreeset! {0, 1}, btreeset! {2}).await?;
        change_from_to_with_add_remove_nodes(btreeset! {0, 1}, btreeset! {3}).await?;
        change_from_to_with_add_remove_nodes(btreeset! {0, 1, 2}, btreeset! {4}).await?;
        change_from_to_with_add_remove_nodes(btreeset! {0, 1, 2}, btreeset! {4,5,6}).await?;
        change_from_to_with_add_remove_nodes(btreeset! {0, 1, 2, 3, 4}, btreeset! {0, 1, 2, 3}).await?;

        Ok::<(), anyhow::Error>(())
    }
    .instrument(ut_span)
    .await?;

    Ok(())
}

#[tracing::instrument(level = "debug")]
async fn change_from_to_with_add_remove_nodes(
    old: BTreeSet<MemNodeId>,
    new: BTreeSet<MemNodeId>,
) -> anyhow::Result<()> {
    let only_in_old = old.difference(&new);
    let only_in_new = new.difference(&old);

    change_from_to_with_remove_add_nodes_api(
        old.clone(),
        only_in_new.cloned().collect::<BTreeSet<_>>(),
        only_in_old.cloned().collect::<BTreeSet<_>>(),
    )
    .await?;

    Ok(())
}
```
___
*[openraft/tests/membership/t16_change_membership_cases.rs, line 119 at r8](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyHD_pHAPIC3lUuRY7m:-MyHD_pHAPIC3lUuRY7n:b-qbh3ze) ([raw file](https://github.com/datafuselabs/openraft/blob/f666fc923034b95b6234acd1f594e245fcdcc0ee/openraft/tests/membership/t16_change_membership_cases.rs#L119)):*
> ```XML
> 
> #[tracing::instrument(level = "debug")]
> async fn change_from_to_with_remove_add_nodes_api(
> ```

Split the tests for add and tests for remove.
They do not have a lot in common.



_Code quote:_
```XML
async fn change_from_to_with_remove_add_nodes_api(
    old: BTreeSet<MemNodeId>,
    add_members: BTreeSet<MemNodeId>,
    remove_members: BTreeSet<MemNodeId>,
) -> anyhow::Result<()> {
```
___
*[openraft/tests/membership/t16_change_membership_cases.rs, line 190 at r8](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyHDRcI7gahALcLixo5:-MyHDRcI7gahALcLixo6:b-x7698f) ([raw file](https://github.com/datafuselabs/openraft/blob/f666fc923034b95b6234acd1f594e245fcdcc0ee/openraft/tests/membership/t16_change_membership_cases.rs#L190)):*
> ```XML
>     router: &mut RaftRouter,
>     mes: String,
>     log_index: &mut u64,
> ```

Why does it have to be a `&mut`?
___
*[openraft/tests/membership/t16_change_membership_cases.rs, line 275 at r8](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyHEUH758JznszpLGFA:-MyHEUH758JznszpLGFB:b-yg42qw) ([raw file](https://github.com/datafuselabs/openraft/blob/f666fc923034b95b6234acd1f594e245fcdcc0ee/openraft/tests/membership/t16_change_membership_cases.rs#L275)):*
> ```XML
> 
>     tracing::info!("--- log will not be sync to removed node");
> ```

Please do not delete my braces...
And deleting them introduces unnecessary changes of blanks.


<!-- Sent from Reviewable.io -->

2022-03-16 12:28 UTC, lichuang reviewed
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/250)* status: 1 of 8 files reviewed, 11 unresolved discussions (waiting on @ariesdevil, @drmingdrmer, and @schreter)

___
*[openraft/tests/membership/t16_change_membership_cases.rs, line 72 at r8](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyHBpwy13v9DyCFI9NW:-MyHglEzDKDI0Mm8Gihn:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/f666fc923034b95b6234acd1f594e245fcdcc0ee/openraft/tests/membership/t16_change_membership_cases.rs#L72)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

These cases are not meant for add/remove member tests.
It's a bit redundant and not very clear about what it tries to prove.


</blockquote></details>

Done.
___
*[openraft/tests/membership/t16_change_membership_cases.rs, line 119 at r8](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyHD_pHAPIC3lUuRY7m:-MyHgifiB02yggvDFRb8:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/f666fc923034b95b6234acd1f594e245fcdcc0ee/openraft/tests/membership/t16_change_membership_cases.rs#L119)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Split the tests for add and tests for remove.
They do not have a lot in common.


</blockquote></details>

Done.
___
*[openraft/tests/membership/t16_change_membership_cases.rs, line 190 at r8](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyHDRcI7gahALcLixo5:-MyHgjcMEZacTkD2sgGy:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/f666fc923034b95b6234acd1f594e245fcdcc0ee/openraft/tests/membership/t16_change_membership_cases.rs#L190)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Why does it have to be a `&mut`?
</blockquote></details>

Done.
___
*[openraft/tests/membership/t16_change_membership_cases.rs, line 275 at r8](https://reviewable.io/reviews/datafuselabs/openraft/250#-MyHEUH758JznszpLGFA:-MyHgkE7EVW7t86yLqwy:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/f666fc923034b95b6234acd1f594e245fcdcc0ee/openraft/tests/membership/t16_change_membership_cases.rs#L275)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Please do not delete my braces...
And deleting them introduces unnecessary changes of blanks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-16 16:16 UTC, drmingdrmer requested changes

2022-03-16 16:16 UTC, drmingdrmer commented on openraft/src/core/admin.rs
> +    ) -> Result<(), ClientWriteError<C>> {
It seems it is possible to make `new_members` a `& BTreeSet`.
That would simplify things a bit.

2022-03-16 16:16 UTC, drmingdrmer commented on openraft/src/core/admin.rs
> +    fn is_all_new_members_line_rate(
This method is not just about `new members`:

```suggestion
    fn are_nodes_at_line_rate(
```

2022-03-16 16:16 UTC, drmingdrmer commented on openraft/tests/membership/t16_change_membership_cases.rs
> +        Ok::<(), anyhow::Error>(())
There should be more cases for both `Add` and `Remove` members.

E.g., for `add_members()`, there should be at least adding an empty set of nodes, adding existent nodes, adding inexistent nodes, etc.

2022-03-17 04:47 UTC, drmingdrmer reviewed
There have been a lot dirty commits in this PR.
A rebase will make the final merge clean:)

2022-03-17 04:47 UTC, drmingdrmer commented on .github/workflows/ci.yaml
> +          RUST_TEST_THREADS: 1
Is this still necessary to pass the CI?

2022-03-17 04:47 UTC, drmingdrmer commented on openraft/src/raft.rs
> +    }
It seems `blocking` is meaningless for `remove_members`.

2022-03-17 07:13 UTC, merged