Refactor: timeout control in votes
datafuselabs/openraft pull request #486
Opened 2022-08-01 08:04 UTC by ClSlaid

Signed-off-by: ClSlaid <cailue@bupt.edu.cn>

This PR solves #467.

1. vote requests should not exceed the timeout of `heartbeat_interval`.
2. timeout will be logged
3. log `JoinError`s in parallel tasks

**Checklist**

- [ ] Updated guide with pertinent info (may not always apply). 
- [x] Squash down commits to one or two logical commits which clearly describe the work you've done.
- [ ] Unittest is a friend:)

2022-08-01 08:57 UTC, drmingdrmer requested changes

2022-08-01 08:57 UTC, drmingdrmer commented on openraft/src/core/raft_core.rs
>          }
Remove these lines. 

`spawn_parallel_vote_requests()` should not block until the task finishes. It should return as soon as tasks spawned.

2022-08-01 09:18 UTC, drmingdrmer approved these changes

2022-08-01 09:18 UTC, drmingdrmer commented on openraft/src/core/raft_core.rs
> +            .map_err(move |e| (target, e));
Remove this line.

2022-08-01 09:18 UTC, drmingdrmer requested changes
Remove the unnecessary map at the bottom. (

2022-08-01 09:19 UTC, ClSlaid commented on openraft/src/core/raft_core.rs
> +            .map_err(move |e| (target, e));
I forgot, sorry.

2022-08-01 09:52 UTC, drmingdrmer approved these changes

2022-08-03 02:23 UTC, drmingdrmer commented
@mergify rebase

2022-08-03 08:46 UTC, merged